In [2]:
import numpy as np
import pandas as pd

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("Day10_Flight_Operations_Dataset.csv")

df["Flight_Date"] = pd.to_datetime(df["Flight_Date"], errors="coerce")

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")
df.head()

Saving Day10_Flight_Operations_Dataset.csv to Day10_Flight_Operations_Dataset.csv
Rows: 180
Columns: 17

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

In [3]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

display(df.head())
display(df.tail())

Shape: (180, 17)

Columns:
['Flight_ID', 'Flight_Date', 'Airline', 'Origin', 'Destination', 'Aircraft', 'Travel_Class', 'Passengers', 'Seat_Capacity', 'Average_Ticket_Price', 'Delay_Minutes', 'Flight_Status', 'Weather', 'Booking_Channel', 'Avg_Baggage_Kg', 'Meal_Preference', 'Passenger_Satisfaction']

Data types:
Flight_ID                         object
Flight_Date               datetime64[ns]
Airline                           object
Origin                            object
Destination                       object
Aircraft                          object
Travel_Class                      object
Passengers                         int64
Seat_Capacity                      int64
Average_Ticket_Price               int64
Delay_Minutes                    float64
Flight_Status                     object
Weather                           object
Booking_Channel                   object
Avg_Baggage_Kg                     int64
Meal_Preference                   object
Passenger_Satisfaction             int64
dtype: object

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
175,FL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5
176,FL0177,2026-02-17,Vistara,Chennai,Mumbai,Airbus A320,Business,124,180,17306,20.0,Delayed,Cloudy,Mobile App,8,No Meal,5
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
178,FL0179,2026-05-08,Vistara,Bengaluru,Kochi,Airbus A320,Economy,134,189,5413,20.0,Delayed,Rain,Online Travel Portal,9,No Meal,2
179,FL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Flight_ID               180 non-null    object
 1   Flight_Date             180 non-null    datetime64[ns]
 2   Airline                 180 non-null    object
 3   Origin                  180 non-null    object
 4   Destination             180 non-null    object
 5   Aircraft                180 non-null    object
 6   Travel_Class            180 non-null    object
 7   Passengers              180 non-null    int64
 8   Seat_Capacity           180 non-null    int64
 9   Average_Ticket_Price    180 non-null    int64
 10  Delay_Minutes           173 non-null    float64
 11  Flight_Status           180 non-null    object
 12  Weather                 180 non-null    object
 13  Booking_Channel         180 non-null    object
 14  Avg_Baggage_Kg          180 non-null    int64
 15  Meal_Preference         180 non-null    object
 16  Passenger_Satisfaction  180 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(10)
memory usage: 24.0+ KB

In [5]:
missing_values = df.isna().sum().sort_values(ascending=False)
display(missing_values.to_frame("Missing_Count"))

print("Duplicate rows:", df.duplicated().sum())

unique_counts = df.nunique().sort_values()
display(unique_counts.to_frame("Unique_Values"))

                        Missing_Count
Delay_Minutes                       7
Flight_ID                           0
Flight_Date                         0
Origin                              0
Airline                             0
Aircraft                            0
Travel_Class                        0
Passengers                          0
Destination                         0
Seat_Capacity                       0
Average_Ticket_Price                0
Flight_Status                       0
Weather                             0
Booking_Channel                     0
Avg_Baggage_Kg                      0
Meal_Preference                     0
Passenger_Satisfaction              0

Duplicate rows: 0

                        Unique_Values
Travel_Class                        3
Flight_Status                       3
Booking_Channel                     4
Aircraft                            4
Meal_Preference                     4
Passenger_Satisfaction              4
Weather                             5
Seat_Capacity                       5
Airline                             6
Destination                         8
Delay_Minutes                       8
Origin                             11
Avg_Baggage_Kg                     21
Flight_Date                       111
Passengers                        115
Average_Ticket_Price              179
Flight_ID                         180

In [7]:
display(df.describe().round(2))

display(df.describe(include="object").T)

,Flight_Date,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Avg_Baggage_Kg,Passenger_Satisfaction
count,180,180.00,180.00,180.00,173.00,180.00,180.00
mean,2026-03-30 18:24:00,122.77,197.24,6111.68,19.34,15.15,3.49
min,2026-01-03 00:00:00,45.00,180.00,1949.00,0.00,5.00,2.00
25%,2026-02-11 12:00:00,78.75,186.00,3815.50,0.00,10.00,2.00
50%,2026-04-01 00:00:00,125.00,189.00,5380.00,5.00,15.50,3.00
75%,2026-05-11 00:00:00,162.25,210.00,6790.00,20.00,20.00,5.00
max,2026-06-29 00:00:00,210.00,220.00,27832.00,110.00,25.00,5.00
std,NaN,45.64,15.41,3615.22,29.03,5.71,1.17

                count unique                   top freq
Flight_ID         180    180                FL0001    1
Airline           180      6               Vistara   37
Origin            180     11                 Delhi   43
Destination       180      8                 Delhi   51
Aircraft          180      4           Airbus A319   60
Travel_Class      180      3               Economy  134
Flight_Status     180      3               On Time  114
Weather           180      5                  Rain   43
Booking_Channel   180      4  Online Travel Portal   50
Meal_Preference   180      4            Vegetarian   52

In [8]:
selected_columns = df[
    ["Flight_ID", "Airline", "Origin", "Destination",
     "Passengers", "Delay_Minutes", "Flight_Status",
     "Passenger_Satisfaction"]
]

display(selected_columns.head(10))

display(
    df.loc[:, ["Flight_ID", "Airline", "Average_Ticket_Price", "Passenger_Satisfaction"]].head(10)
)

,Flight_ID,Airline,Origin,Destination,Passengers,Delay_Minutes,Flight_Status,Passenger_Satisfaction
0,FL0001,SpiceJet,Mumbai,Bengaluru,210,50.0,Delayed,3
1,FL0002,Akasa Air,Delhi,Mumbai,70,0.0,On Time,5
2,FL0003,Air India,Kochi,Delhi,67,5.0,On Time,2
3,FL0004,Akasa Air,Srinagar,Delhi,153,35.0,Delayed,2
4,FL0005,Air India,Pune,Delhi,178,20.0,Delayed,5
5,FL0006,Akasa Air,Kochi,Delhi,123,35.0,Delayed,2
6,FL0007,Air India Express,Delhi,Srinagar,178,0.0,On Time,4
7,FL0008,Air India,Delhi,Chennai,157,0.0,On Time,5
8,FL0009,Akasa Air,Delhi,Chennai,82,75.0,Delayed,4
9,FL0010,Akasa Air,Ahmedabad,Bengaluru,125,12.0,On Time,4

  Flight_ID            Airline  Average_Ticket_Price  Passenger_Satisfaction
0    FL0001           SpiceJet                  6894                       3
1    FL0002          Akasa Air                  4468                       5
2    FL0003          Air India                  4713                       2
3    FL0004          Akasa Air                  3791                       2
4    FL0005          Air India                  6505                       5
5    FL0006          Akasa Air                  5636                       2
6    FL0007  Air India Express                  9430                       4
7    FL0008          Air India                 14173                       5
8    FL0009          Akasa Air                  5893                       4
9    FL0010          Akasa Air                  2500                       4

In [9]:
delayed_30 = df[df["Delay_Minutes"] > 30]
print("Flights delayed more than 30 minutes:", len(delayed_30))
display(delayed_30[
    ["Flight_ID", "Airline", "Origin", "Destination", "Delay_Minutes", "Weather"]
].head(10))

high_satisfaction = df[df["Passenger_Satisfaction"] >= 8]
print("Flights with satisfaction >= 8:", len(high_satisfaction))

high_delay_low_satisfaction = df[
    (df["Delay_Minutes"] > 30) &
    (df["Passenger_Satisfaction"] < 7)
]
print("Flights with delay > 30 min and satisfaction < 7:", len(high_delay_low_satisfaction))
display(high_delay_low_satisfaction.head(10))

Flights delayed more than 30 minutes: 40

   Flight_ID    Airline     Origin Destination  Delay_Minutes Weather
0     FL0001   SpiceJet     Mumbai   Bengaluru           50.0   Storm
3     FL0004  Akasa Air   Srinagar       Delhi           35.0   Storm
5     FL0006  Akasa Air      Kochi       Delhi           35.0  Cloudy
8     FL0009  Akasa Air      Delhi     Chennai           75.0  Cloudy
21    FL0022    Vistara      Kochi       Delhi           75.0   Clear
26    FL0027   SpiceJet  Bengaluru   Hyderabad          110.0   Clear
29    FL0030   SpiceJet      Delhi    Srinagar           75.0   Storm
30    FL0031    Vistara      Delhi    Srinagar           50.0  Cloudy
32    FL0033  Akasa Air  Ahmedabad   Bengaluru           35.0  Cloudy
42    FL0043    Vistara      Delhi     Chennai           50.0   Clear

Flights with satisfaction >= 8: 0
Flights with delay > 30 min and satisfaction < 7: 40

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
5,FL0006,2026-05-20,Akasa Air,Kochi,Delhi,Airbus A319,Economy,123,220,5636,35.0,Delayed,Cloudy,Travel Agency,13,Vegetarian,2
8,FL0009,2026-01-25,Akasa Air,Delhi,Chennai,Airbus A320,Economy,82,210,5893,75.0,Delayed,Cloudy,Mobile App,8,Vegetarian,4
21,FL0022,2026-02-01,Vistara,Kochi,Delhi,Airbus A321,Economy,126,220,5887,75.0,Delayed,Clear,Airline Website,10,Vegetarian,2
26,FL0027,2026-02-10,SpiceJet,Bengaluru,Hyderabad,Airbus A319,Economy,169,180,3973,110.0,Delayed,Clear,Mobile App,7,Vegan,4
29,FL0030,2026-04-10,SpiceJet,Delhi,Srinagar,Airbus A321,Economy,200,210,2716,75.0,Delayed,Storm,Airline Website,10,Vegan,3
30,FL0031,2026-01-08,Vistara,Delhi,Srinagar,Airbus A321,Premium Economy,209,180,9962,50.0,Delayed,Cloudy,Mobile App,9,Vegetarian,4
32,FL0033,2026-04-27,Akasa Air,Ahmedabad,Bengaluru,Boeing 737,Business,66,180,17625,35.0,Delayed,Cloudy,Mobile App,15,No Meal,4
42,FL0043,2026-06-19,Vistara,Delhi,Chennai,Airbus A319,Economy,64,220,4029,50.0,Delayed,Clear,Mobile App,5,No Meal,3

In [10]:
display(
    df.sort_values("Delay_Minutes", ascending=False)[
        ["Flight_ID", "Airline", "Origin", "Destination", "Delay_Minutes", "Flight_Status"]
    ].head(10)
)

display(
    df.sort_values("Passenger_Satisfaction", ascending=False)[
        ["Flight_ID", "Airline", "Passenger_Satisfaction", "Delay_Minutes"]
    ].head(10)
)

,Flight_ID,Airline,Origin,Destination,Delay_Minutes,Flight_Status
26,FL0027,SpiceJet,Bengaluru,Hyderabad,110.0,Delayed
177,FL0178,IndiGo,Delhi,Mumbai,110.0,Delayed
82,FL0083,Air India Express,Lucknow,Delhi,110.0,Delayed
57,FL0058,IndiGo,Hyderabad,Kolkata,110.0,Delayed
50,FL0051,Air India,Delhi,Mumbai,110.0,Delayed
128,FL0129,SpiceJet,Lucknow,Delhi,110.0,Delayed
146,FL0147,IndiGo,Mumbai,Kolkata,110.0,Delayed
169,FL0170,IndiGo,Mumbai,Kolkata,110.0,Delayed
161,FL0162,Air India,Hyderabad,Kolkata,110.0,Delayed
21,FL0022,Vistara,Kochi,Delhi,75.0,Delayed

   Flight_ID    Airline  Passenger_Satisfaction  Delay_Minutes
1     FL0002  Akasa Air                       5            0.0
13    FL0014  Air India                       5            0.0
7     FL0008  Air India                       5            0.0
4     FL0005  Air India                       5           20.0
19    FL0020   SpiceJet                       5           12.0
14    FL0015  Akasa Air                       5            0.0
12    FL0013   SpiceJet                       5            0.0
47    FL0048  Air India                       5           20.0
37    FL0038  Air India                       5            NaN
41    FL0042     IndiGo                       5           12.0

In [11]:
df["Load_Factor_%"] = (df["Passengers"] / df["Seat_Capacity"] * 100).round(2)

df["Revenue_Estimate"] = df["Passengers"] * df["Average_Ticket_Price"]

df["Delay_Category"] = pd.cut(
    df["Delay_Minutes"],
    bins=[-np.inf, 0, 15, 60, np.inf],
    labels=["On time", "Minor (1–15 min)", "Moderate (16–60 min)", "Severe (>60 min)"]
)

display(
    df[
        ["Flight_ID", "Passengers", "Seat_Capacity", "Load_Factor_%",
         "Average_Ticket_Price", "Revenue_Estimate", "Delay_Minutes", "Delay_Category"]
    ].head(10)
)

,Flight_ID,Passengers,Seat_Capacity,Load_Factor_%,Average_Ticket_Price,Revenue_Estimate,Delay_Minutes,Delay_Category
0,FL0001,210,180,116.67,6894,1447740,50.0,Moderate (16–60 min)
1,FL0002,70,210,33.33,4468,312760,0.0,On time
2,FL0003,67,220,30.45,4713,315771,5.0,Minor (1–15 min)
3,FL0004,153,220,69.55,3791,580023,35.0,Moderate (16–60 min)
4,FL0005,178,180,98.89,6505,1157890,20.0,Moderate (16–60 min)
5,FL0006,123,220,55.91,5636,693228,35.0,Moderate (16–60 min)
6,FL0007,178,210,84.76,9430,1678540,0.0,On time
7,FL0008,157,220,71.36,14173,2225161,0.0,On time
8,FL0009,82,210,39.05,5893,483226,75.0,Severe (>60 min)
9,FL0010,125,220,56.82,2500,312500,12.0,Minor (1–15 min)

In [12]:
airline_summary = (
    df.groupby("Airline")
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Avg_Delay_Min=("Delay_Minutes", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean"),
          Avg_Load_Factor=("Load_Factor_%", "mean"),
          Estimated_Revenue=("Revenue_Estimate", "sum")
      )
      .sort_values("Estimated_Revenue", ascending=False)
      .round(2)
)

display(airline_summary)

,Flights,Passengers,Avg_Delay_Min,Avg_Satisfaction,Avg_Load_Factor,Estimated_Revenue
Airline,,,,,,
Vistara,37,4484,18.63,3.38,61.87,28689467
IndiGo,32,4158,25.03,3.34,66.78,25709131
SpiceJet,32,3929,24.14,3.53,63.60,24195935
Air India Express,24,3027,11.29,3.67,64.79,23944164
Akasa Air,31,3427,14.40,3.42,55.21,18872059
Air India,24,3074,21.26,3.75,64.65,16232418

In [13]:
status_summary = (
    df.groupby("Flight_Status")
      .agg(
          Flights=("Flight_ID", "count"),
          Avg_Delay_Min=("Delay_Minutes", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean")
      )
      .sort_values("Flights", ascending=False)
      .round(2)
)

display(status_summary)

               Flights  Avg_Delay_Min  Avg_Satisfaction
Flight_Status
On Time            114           3.46              3.59
Delayed             59          50.00              3.27
Cancelled            7            NaN              3.86

In [14]:
class_summary = (
    df.groupby("Travel_Class")
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Avg_Ticket_Price=("Average_Ticket_Price", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean"),
          Avg_Baggage_Kg=("Avg_Baggage_Kg", "mean")
      )
      .sort_values("Passengers", ascending=False)
      .round(2)
)

display(class_summary)

,Flights,Passengers,Avg_Ticket_Price,Avg_Satisfaction,Avg_Baggage_Kg
Travel_Class,,,,,
Economy,134,16054,4550.27,3.46,14.89
Premium Economy,35,4574,8736.74,3.69,16.37
Business,11,1471,16780.00,3.27,14.45

In [15]:
weather_summary = (
    df.groupby("Weather")
      .agg(
          Flights=("Flight_ID", "count"),
          Avg_Delay_Min=("Delay_Minutes", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean")
      )
      .sort_values("Avg_Delay_Min", ascending=False)
      .round(2)
)

display(weather_summary)

         Flights  Avg_Delay_Min  Avg_Satisfaction
Weather
Rain          43          22.22              3.37
Storm         30          20.10              3.17
Cloudy        38          20.03              3.84
Clear         34          18.03              3.35
Fog           35          15.79              3.69

In [16]:
route_summary = (
    df.groupby(["Origin", "Destination"])
      .agg(
          Flights=("Flight_ID", "count"),
          Passengers=("Passengers", "sum"),
          Avg_Delay_Min=("Delay_Minutes", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean"),
          Avg_Load_Factor=("Load_Factor_%", "mean")
      )
      .sort_values("Passengers", ascending=False)
      .round(2)
)

display(route_summary.head(15))

,,Flights,Passengers,Avg_Delay_Min,Avg_Satisfaction,Avg_Load_Factor
Origin,Destination,,,,,
Delhi,Chennai,17,2011,19.00,3.47,59.23
Srinagar,Delhi,15,1957,16.36,3.27,65.12
Mumbai,Bengaluru,16,1933,15.44,3.25,63.85
Delhi,Srinagar,13,1828,18.92,3.31,71.16
Bengaluru,Hyderabad,13,1795,15.38,3.77,71.55
Mumbai,Kolkata,13,1683,27.00,3.92,66.34
Kochi,Delhi,14,1657,15.00,3.50,60.13
Delhi,Mumbai,13,1609,39.18,3.54,62.69
Pune,Delhi,11,1564,5.55,3.73,73.71
Ahmedabad,Bengaluru,12,1411,11.45,3.92,58.89
Lucknow,Delhi,11,1137,40.00,3.18,53.30
Jaipur,Mumbai,8,962,10.00,3.38,61.66
Bengaluru,Kochi,8,930,3.12,3.38,59.75
Hyderabad,Kolkata,7,884,51.71,3.86,64.13
Chennai,Mumbai,9,738,7.44,3.00,41.75

In [17]:
channel_summary = (
    df.groupby("Booking_Channel")
      .agg(
          Flights=("Flight_ID", "count"),
          Avg_Ticket_Price=("Average_Ticket_Price", "mean"),
          Avg_Satisfaction=("Passenger_Satisfaction", "mean"),
          Avg_Delay_Min=("Delay_Minutes", "mean")
      )
      .sort_values("Flights", ascending=False)
      .round(2)
)

display(channel_summary)

,Flights,Avg_Ticket_Price,Avg_Satisfaction,Avg_Delay_Min
Booking_Channel,,,,
Online Travel Portal,50,5636.28,3.74,23.08
Mobile App,45,6637.24,3.44,24.95
Travel Agency,44,6223.89,3.39,12.28
Airline Website,41,5994.17,3.37,15.85

In [18]:
top_delays = df.nlargest(10, "Delay_Minutes")[
    ["Flight_ID", "Airline", "Origin", "Destination",
     "Delay_Minutes", "Weather", "Flight_Status"]
]

display(top_delays)

,Flight_ID,Airline,Origin,Destination,Delay_Minutes,Weather,Flight_Status
26,FL0027,SpiceJet,Bengaluru,Hyderabad,110.0,Clear,Delayed
50,FL0051,Air India,Delhi,Mumbai,110.0,Rain,Delayed
57,FL0058,IndiGo,Hyderabad,Kolkata,110.0,Cloudy,Delayed
82,FL0083,Air India Express,Lucknow,Delhi,110.0,Cloudy,Delayed
128,FL0129,SpiceJet,Lucknow,Delhi,110.0,Cloudy,Delayed
146,FL0147,IndiGo,Mumbai,Kolkata,110.0,Rain,Delayed
161,FL0162,Air India,Hyderabad,Kolkata,110.0,Rain,Delayed
169,FL0170,IndiGo,Mumbai,Kolkata,110.0,Rain,Delayed
177,FL0178,IndiGo,Delhi,Mumbai,110.0,Fog,Delayed
8,FL0009,Akasa Air,Delhi,Chennai,75.0,Cloudy,Delayed